package by.project.news.controller;

public enum CommandName {

	REGISTRATION, AUTHORIZATION, USER_TOOLS, USER_ANSWER, INDEX, USER_AUTHORIZATION, USER_REGISTRATION, MAIN,
	USER_UPDATE, USER_DELETE, USER_PASSWORD, USER_TOOLS_UPDATE, USER_TOOLS_DELETE, USER_TOOLS_PASSWORD, LOGGEDOUT,
	NEWS_TOOLS, NEWS_ADD, NEWS_UPDATE, NEWS_DELETE, NEWS_ANSWER, NEWS_CHOOSE, NEWS_TOOLS_ADD, NEWS_TOOLS_UPDATE,
	NEWS_TOOLS_DELETE, NEWS_TOOLS_CHOOSE, NEWS_VIEW, NEWS_SGNAUTHOR, NEWS_TOOLS_SGN, NEWS_TOOLS_UNSGN,
	NEWS_TOOLS_SGNVIEW, UNKNOWN_COMMAND, CHANGE_LOCAL,
	;
}
